# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:        
    
    access_control:
#        - { path: ^/usuario, roles: ROLE_BECARIO }
        - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_BECARIO] }
        - { path: ^/role-check, roles: [ IS_AUTHENTICATED_ANONYMOUSLY,ROLE_ADMIN, ROLE_BECARIO ] }
        - { path: /, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        
    encoders:
        BackendBundle\Entity\Usuario:
            algorithm: bcrypt
            cost: 4

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_db_provider:
            entity:
                class: BackendBundle:Usuario
                property: nombreusuario
                
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_db_provider
            form_login:
                login_path: /
                check_path: /login_check
            logout: 
                path: logout
                target: /
                
            # activate different ways to authenticate

            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
            #form_login: ~
