## YAML Template.
---
login:
    path: /login
    defaults: { _controller: BackendBundle:Default:index }

login_check:
    path: /login_check
    
logout:
    path: /logout
    
role_check:
    path: /role-check
    defaults: { _controller: BackendBundle:Default:roleCheck }